/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antiufieievmichael_NativeBridge */

#ifndef _Included_com_antiufieievmichael_NativeBridge
#define _Included_com_antiufieievmichael_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antiufieievmichael_NativeBridge
 * Method:    example
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antiufieievmichael_NativeBridge_example(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
