name: Ubuntu Build

on:
  push:
    branches:
      - main
      - fix/ci
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform-agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            COMPILER: g++-8
            LINKER: g++-8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get -y install g++-8
          sudo apt-get -y install freeglut3-dev
          sudo apt-get -y install libglew-dev
          sudo apt-get -y install libglfw3-dev
          vcpkg install ktx:x64-linux
      - name: Setup GCC
        run: |
          sudo rm /usr/bin/gcc
          sudo rm /usr/bin/g++
          sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
          sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
          export CC=/usr/bin/gcc-8
          export CXX=/usr/bin/g++-8
          gcc -v && g++ -v && cmake --version
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
